In [48]:
tickers = [
    "AAPL", "ABNB", "ADBE", "ADI", "ADP", "ADSK", "AEP", "AMAT", "AMD", "AMGN",
    "AMZN", "ANSS", "APP", "ARM", "ASML", "AVGO", "AXON", "AZN", "BIIB", "BKNG",
    "BKR", "CCEP", "CDNS", "CDW", "CEG", "CHTR", "CMCSA", "COST", "CPRT", "CRWD",
    "CSCO", "CSGP", "CSX", "CTAS", "CTSH", "DASH", "DDOG", "DXCM", "EA", "EXC",
    "FANG", "FAST", "FTNT", "GEHC", "GFS", "GILD", "GOOG", "GOOGL", "HON", "IDXX",
    "INTC", "INTU", "ISRG", "KDP", "KHC", "KLAC", "LIN", "LRCX", "LULU", "MAR",
    "MCHP", "MDB", "MDLZ", "MELI", "META", "MNST", "MRVL", "MSFT", "MSTR", "MU",
    "NFLX", "NVDA", "NXPI", "ODFL", "ON", "ORLY", "PANW", "PAYX", "PCAR", "PDD",
    "PEP", "PLTR", "PYPL", "QCOM", "REGN", "ROP", "ROST", "SBUX", "SNPS", "TEAM",
    "TMUS", "TSLA", "TTD", "TTWO", "TXN", "VRSK", "VRTX", "WBD", "WDAY", "XEL", "ZS"
]

In [49]:
import requests
import json
import pandas as pd
from datetime import datetime
from dotenv import load_dotenv
import os

In [50]:
url = "/uapi/overseas-price/v1/quotations/inquire-daily-chartprice"

load_dotenv()

my_app= os.getenv("MY_APP")
my_sec= os.getenv("MY_SEC")

#계좌번호 앞 8자리
my_acct="43016876"
my_acct_stock= "증권계좌 8자리"
my_acct_future= "선물옵션계좌 8자리"
#계좌번호 뒤 2자리
my_prod= "01"
#my_prod: "03"

#실전투자
prod= "https://openapi.koreainvestment.com:9443"
#모의투자
vps= "https://openapivts.koreainvestment.com:29443"


my_agent= "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36"

class Env:
    def __init__(self):
        self.my_app = my_app
        self.my_sec = my_sec
        self.my_url = prod
        self.my_token = None
        self.my_acct = my_acct
        self.my_prod = my_prod
_env = Env()

In [51]:
def auth():
    url = f'{_env.my_url}/oauth2/tokenP'
    headers = {"content": "application/json"}
    data = {
        "grant_type":"client_credentials",
        "appkey": _env.my_app,
        "appsecret": _env.my_sec
    }

    res = requests.post(url, headers=headers, data= json.dumps(data))
    if res.status_code == 200:
        print('토큰 발급 성공')
        _env.my_token = res.json()['access_token']
    else:
        print("토큰 발급 실패")
        print(res.status_code, res.text)

In [52]:
auth()

토큰 발급 성공

In [65]:
headers = {
    "Content-Type": "application/json",
    "authorization": f'Bearer {_env.my_token}',
    "appkey": _env.my_app,
    "appsecret": _env.my_sec,
    "tr_id": "FHKST03030100", 
    "custtype": "P"
}

In [66]:
params = {
    "FID_COND_MRKT_DIV_CODE": "N",
    "FID_INPUT_DATE_1": "20240101",
    "FID_INPUT_DATE_2": "20241231",
    "FID_PERIOD_DIV_CODE": 'M'
}

In [67]:
my_url=_env.my_url+url
li = []
for ticker in tickers:
    params['FID_INPUT_ISCD'] = ticker
    params['SYMB'] = ticker
    response = requests.get(my_url, headers=headers, params=params)
    if response.status_code != 200:
        print('조회 실패')
    else:
        print('조회 성공')
        data = response.json()['output2']
    li.append(data)
print(len(li))

조회 성공
조회 성공
조회 성공
조회 성공
조회 성공
조회 성공
조회 성공
조회 성공
조회 성공
조회 성공
조회 성공
조회 성공
조회 성공
조회 성공
조회 성공
조회 성공
조회 성공
조회 성공
조회 성공
조회 성공
조회 성공
조회 성공
조회 성공
조회 성공
조회 성공
조회 성공
조회 성공
조회 성공
조회 성공
조회 성공
조회 성공
조회 성공
조회 성공
조회 성공
조회 성공
조회 성공
조회 성공
조회 성공
조회 성공
조회 성공
조회 성공
조회 성공
조회 성공
조회 성공
조회 성공
조회 성공
조회 성공
조회 성공
조회 성공
조회 성공
조회 성공
조회 성공
조회 성공
조회 성공
조회 성공
조회 성공
조회 성공
조회 성공
조회 성공
조회 성공
조회 성공
조회 성공
조회 성공
조회 성공
조회 성공
조회 성공
조회 성공
조회 성공
조회 성공
조회 성공
조회 성공
조회 성공
조회 성공
조회 성공
조회 성공
조회 성공
조회 성공
조회 성공
조회 성공
조회 성공
조회 성공
조회 성공
조회 성공
조회 성공
조회 성공
조회 성공
조회 성공
조회 성공
조회 성공
조회 성공
조회 성공
조회 성공
조회 성공
조회 성공
조회 성공
조회 성공
조회 성공
조회 성공
조회 성공
조회 성공
조회 성공
101

In [68]:
len(li)

101

In [73]:
pd.DataFrame(li[0])

,stck_bsop_date,ovrs_nmix_prpr,ovrs_nmix_oprc,ovrs_nmix_hgpr,ovrs_nmix_lwpr,acml_vol,mod_yn
0,20241201,250.42,237.27,260.10,237.16,977942014,N
1,20241101,237.33,220.96,237.81,219.71,891640714,N
2,20241001,225.91,229.52,237.49,221.33,930835961,N
3,20240901,233.00,228.55,233.09,213.92,1232391861,N
4,20240801,229.00,224.37,232.92,196.00,1122588393,N
5,20240701,222.08,212.09,237.23,211.92,1153193377,N
6,20240601,210.62,192.90,220.20,192.15,1723984420,N
7,20240501,192.25,169.58,193.00,169.11,1336570142,N
8,20240401,170.33,171.19,178.36,164.07,1246221542,N
9,20240301,171.48,179.55,180.53,168.49,1431757820,N
10,20240201,180.75,183.99,191.05,179.25,1161711745,N
11,20240101,184.40,187.15,196.38,180.17,1187490645,N

In [74]:
params['FID_INPUT_ISCD'] = "AAPL"
response = requests.get(my_url, headers=headers, params=params)

In [78]:
data = response.json()

In [80]:
data['output2'][0]

{'stck_bsop_date': '20241201',
 'ovrs_nmix_prpr': '250.42',
 'ovrs_nmix_oprc': '237.27',
 'ovrs_nmix_hgpr': '260.10',
 'ovrs_nmix_lwpr': '237.16',
 'acml_vol': '977942014',
 'mod_yn': 'N'}